# Approved field schemas and business rules; no credentials, endpoints or customer records.

BULK_IMPORT_DATA_TEMPLE_API = {
    "title": None,
    "englishName": None,
    "membershipstartdate": None,
    "chineseName": None,
    "dateOfBirth": None,
    "ageGroup": None,
    "martial": None,
    "education": None,
    "room": None,
    "floor": None,
    "block": None,
    "buildingName": None,
    "estateName": None,
    "lowStreetNo": None,
    "hiStreetNo": None,
    "streetName": None,
    "district": None,
    "districtId": None,
    "country": None,
    "province": None,
    "city": None,
    "address1": None,
    "address2": None,
    "postCode": None,
    "residenceId": None,
    "homePhone": None,
    "mobile": None,
    "emailAddress": None,
    "annualIncome": None,
    "membershipType": None,
    "addressLanguage": None,
    "applicationDate": None,
    "serialNumber": None,
    "filePropertyCode": None,
    "starBlock": None,
    "starFloor": None,
    "starFlat": None,
    "biSerialNo": None,
    "callVerifyFlag": None,
    "optOut":None,
    "optOutPhone": None,
    "optOutSms": None,
    "optOutPost": None,
    "giftCode": None,
    "hkPr": None,
    "isRelative": None,
    "companyName": None,
    "brNo": None,
    "authPerson": None,
    "authCompany": None,
    "noOfPropertyPurchase": None,
    "isAgent": None,
    "Questionnaire_Answer1": None,
    "Questionnaire_Answer2": None,
    "Questionnaire_Answer3": None,
    "Questionnaire_Answer4": None,
    "Questionnaire_Answer5": None,
    "Questionnaire_Answer6": None,
    "Questionnaire_Answer7": None,
    "Questionnaire_Answer8": None,
    'FullAddress': None,
    'othermobile': None,
    'T38_Ballot_Id': None,
    'hashed_hkid': None,
    "Consent_to_join_SHKP_club": None,
    "Full Name  ↑": None,
    "Full Name: Main Guest(Formstack)": None,
    "Email : Main Guest (Formstack)": None,
    "Mobile: Main Guest(Formstack)": None,
    "Full Name: Family Member 1(Formstack)": None,
    "Birth Date: Family member 1": None,
    "Full Name: Family Member 2(Formstack)": None,
    "Mobile: Family member 1(Formstack)": None,
    "Email : Family member 1 (Formstack)": None,
    "Full Name: Family Member 2(Formstack)": None,
    "Birth Date: Family member 2": None,
    "First Name": None,
    "Last Name": None,
    "Country Code (Mobile)": None,
    "Mobile Phone": None,
    "Mobile Phone 2": None,
    "Mobile": None,
    "Work Phone": None
}

BULK_IMPORT_DATA_TEMPLE_API_V2 = {
    "title": None,
    "englishName": None,
    "chineseName": None,
    "dateOfBirth": None,
    "ageGroup": None,
    "martial": None,
    "education": None,
    "room": None,
    "floor": None,
    "block": None,
    "buildingName": None,
    "estateName": None,
    "lowStreetNo": None,
    "hiStreetNo": None,
    "streetName": None,
    "district": None,
    "districtId": None,
    "country": None,
    "province": None,
    "city": None,
    "address1": None,
    "address2": None,
    "postCode": None,
    "residenceId": None,
    "homePhone": None,
    "mobile": None,
    "emailAddress": None,
    "annualIncome": None,
    "membershipType": None,
    "addressLanguage": None,
    "applicationDate": None,
    "serialNumber": None,
    "filePropertyCode": None,
    "starBlock": None,
    "starFloor": None,
    "starFlat": None,
    "biSerialNo": None,
    "callVerifyFlag": None,
    "optOut": None,
    "optOutPhone": None,
    "optOutSms": None,
    "optOutPost": None,
    "giftCode": None,
    "hkPr": None,
    "isRelative": None,
    "companyName": None,
    "brNo": None,
    "authPerson": None,
    "authCompany": None,
    "noOfPropertyPurchase": None,
    "isAgent": None,
    "Questionnaire_Answer1": None,
    "Questionnaire_Answer2": None,
    "Questionnaire_Answer3": None,
    "Questionnaire_Answer4": None,
    "Questionnaire_Answer5": None,
    "Questionnaire_Answer6": None,
    "Questionnaire_Answer7": None,
    "Questionnaire_Answer8": None,
    'FullAddress': None,
    'othermobile': None,
    'T38_Ballot_Id': None,
    'membershipstartdate': None,
    'hashed_hkid': None
}

BULK_ROI_MAPPING_API = {
    "title": "TITLE",
    "englishName": "ENGLISH_NAME",
    "chineseName": "CHINESE_NAME",
    "dateOfBirth": "DOB",
    "ageGroup": "AGE_GP",
    "martial": "MARITAL_STATUS",
    "education": "EDUCATION",
    "room": "UNIT",
    "floor": "FLOOR",
    "block": "ESTA_BLK1",
    "buildingName": "BUILDING_NAME",
    "estateName": "ESTATE",
    "lowStreetNo": "STNO_FROM",
    "hiStreetNo": "STNO_TO",
    "streetName": "STREET",
    "district": "DISTRICT_18",
    "districtId": None,
    "country": None,
    "province": None,
    "city": None,
    "address1": "A_BLOCK",
    "address2": None,
    "postCode": "POST_CODE",
    "residenceId": None,
    "homePhone": "HOME_PHONE",
    "mobile": "MOBILE_NO",
    "emailAddress": "EMAIL_ADDRESS",
    "annualIncome": "ANNUAL_INCOME",
    "membershipType": "MEMBERSHIP_TYPE",
    "addressLanguage": "ADDRESS_LANGUAGE",
    "applicationDate": "APPLICANTION_DATE",
    "serialNumber": "SERIAL_NO",
    "membershipstartdate": "MEMBERSHIP_START_DATE",
    "filePropertyCode": "PID",
    "starBlock": "BUY_BLOCK",
    "starFloor": "BUY_FLOOR",
    "starFlat": "BUY_FLAT",
    "biSerialNo": "T38_REGISTRATION_NUMBER",
    "callVerifyFlag": "VERIFIED",
    "optOut": "DONT_TRANSFER_DATA_SHKP_CLUB",
    "optOutPhone": "DONT_TRANSFER_DATA_SHKP_CLUB",
    "optOutSms": "DONT_TRANSFER_DATA_SHKP_CLUB",
    "optOutPost": "DONT_TRANSFER_DATA_SHKP_CLUB",
    "giftCode": "GIFT_CODE",
    "hkPr": "HKID_TYPE",
    "isRelative": "RELATIVE",
    "companyName": "COMPANY_NAME",
    "brNo": "BR_NO",
    "authPerson": "AUTHORISATION_FOR_SUBMISSION_PERSON",
    "authCompany": "AUTHORISATION_FOR_SUBMISSION_COMPANY",
    "noOfPropertyPurchase": "PROPERTY_PREFERENCE",
    "isAgent": "AGENT",
    "Questionnaire_Answer1": "Q1",
    "Questionnaire_Answer2": "Q2",
    "Questionnaire_Answer3": "Q3",
    "Questionnaire_Answer4": "Q4",
    "Questionnaire_Answer5": "Q5",
    "Questionnaire_Answer6": "Q6",
    "Questionnaire_Answer7": "Q7",
    "Questionnaire_Answer8": "Q8",
    "FullAddress": "A_BLOCK",
    "OtherMobile": None,
    'T38_Ballot_Id': "T38_BALLOT_ID",
    "hashed_hkid": "HASHED_HKID"
}

TITLE_MAPPING = {
    "MR": 1,
    "MISS": 2,
    "MRS": 3,
    "MS": 4,
}

AGE_GROUP_MAPPING = {
    "0-17": -1,
    "18-21": 18,
    "22-25": 22,
    "26-29": 26,
    "30-33": 30,
    "34-37": 34,
    "38-41": 38,
    "42-45": 42,
    "46-49": 46,
    "50-53": 50,
    "54-57": 54,
    "58-61": 58,
    "62-65": 62,
    "65 or above": 65,
    "Unknown": 0,
}

SOURCE_FIELDS: list[str] = [
    "serial_number",
    "activate_status",
    "distribution",
    "verify_email",
    "valid_mobile",
    "valid_email",
    "opt_out",
    "opt_out_phone",
    "opt_out_sms",
    "opt_out_post",
    "membership_start_date",
    "date_of_birth",
    "education",
    "age_group",
    "marital",
    "star_approval_date",
    "received_date",
    "application_date",
    "approval_date",
]

DATE_COLUMNS_PAIRED: list[str] = [
    "membership_start_date_retained",
    "membership_start_date_terminated",
    "star_approval_date_retained",
    "star_approval_date_terminated",
    "received_date_retained",
    "received_date_terminated",
    "application_date_retained",
    "application_date_terminated",
    "approval_date_retained",
    "approval_date_terminated",
]

BLOCKED_ACTIVATE_STATUS: list[str] = [
    "Download to wallet pass",
    "Show membership card with QR code",
]

REPLACE_WHEN_TERMINATED_IS_NEWER: dict[str, str] = {
    "valid_email_retained": "valid_email_terminated",
    "opt_out_retained": "opt_out_terminated",
    "opt_out_phone_retained": "opt_out_phone_terminated",
    "opt_out_sms_retained": "opt_out_sms_terminated",
    "opt_out_post_retained": "opt_out_post_terminated",
    "education_retained": "education_terminated",
    "age_group_retained": "age_group_terminated",
    "marital_retained": "marital_terminated",
    "distribution_retained": "distribution_terminated"
}

MIN_DATE_BASES: list[str] = [
    "membership_start_date",
    "received_date",
    "application_date",
    "approval_date",
    "star_approval_date",
]

TEMPLATE_COLUMN_MAPPING: dict[str, str] = {
    "Retained_SN": "Serial No",
    "distribution_retained": "distribution id",
    "opt_out_retained": "optout",
    "opt_out_phone_retained": "optout call",
    "opt_out_sms_retained": "optout sms",
    "opt_out_post_retained": "optout post",
    "verify_email_retained": "verify_email",
    "valid_mobile_retained": "valid_mobile",
    "membership_start_date_retained": "membership start date",
    "date_of_birth_retained": "date_of_birth",
    "education_retained": "educational_id",
    "age_group_retained": "age_group",
    "marital_retained": "marital_id",
    "star_approval_date_retained": "star_approval_date",
    "received_date_retained": "received_date",
    "application_date_retained": "application_date",
    "approval_date_retained": "approval_date",
}

TEMPLATE_DATE_COLUMNS: list[str] = [
    "effective date",
    "membership start date",
    "date_of_birth",
    "star_approval_date",
    "received_date",
    "application_date",
    "approval_date",
]
